name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: sahil0052
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & push snake SVG
        run: |
          git config --global user.name "Sahil Sharma"
          git config --global user.email "lavisarswat1234@gmail.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution snake" || echo "Nothing to commit"
          git push
