name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git config
        run: |
          git config --global user.name "Sahil Sharma"
          git config --global user.email "lavisarswat1234@gmail.com"

      - name: Ensure dist folder exists
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: sahil0052
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        run: |
          git fetch origin output || git checkout --orphan output
          git checkout -B output
          git add dist/*
          git commit -m "Update contribution snake" || echo "Nothing to commit"
          git push -f origin output
